name: Build ProSoccerOnline ESP EXE

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymem PyQt5 pyinstaller pywin32

    - name: Build ProSoccerOnline ESP with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --uac-admin --name="ProSoccer_EPS" esp.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ProSoccer-ESP-Executable
        path: dist/ProSoccer_EPS.exe
        if-no-files-found: error
        retention-days: 5
